// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6vIowztloZ-r3phYNSEkXLx1eLRqJHiY',
    appId: '1:227304993843:web:207d062baf44928df85f46',
    messagingSenderId: '227304993843',
    projectId: 'test-df3df',
    authDomain: 'test-df3df.firebaseapp.com',
    storageBucket: 'test-df3df.appspot.com',
    measurementId: 'G-9G2EHZBZHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXoeZ4d_NxlSIcolA9a3zu3YMr3KAsHGc',
    appId: '1:227304993843:android:5314956dc6d8c078f85f46',
    messagingSenderId: '227304993843',
    projectId: 'test-df3df',
    storageBucket: 'test-df3df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB-qTcJ2-3lu7ZokvDR0OSNaOjJMwqhRA',
    appId: '1:227304993843:ios:51c603c2b12cb1a4f85f46',
    messagingSenderId: '227304993843',
    projectId: 'test-df3df',
    storageBucket: 'test-df3df.appspot.com',
    iosBundleId: 'com.egkarin.ch09Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB-qTcJ2-3lu7ZokvDR0OSNaOjJMwqhRA',
    appId: '1:227304993843:ios:51c603c2b12cb1a4f85f46',
    messagingSenderId: '227304993843',
    projectId: 'test-df3df',
    storageBucket: 'test-df3df.appspot.com',
    iosBundleId: 'com.egkarin.ch09Flutter',
  );
}
